In [70]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [71]:
df = pd.read_csv('/Applications/Repos/Repo/expedition/Python/Stocks/World-Stock-Prices-Dataset.csv')

In [72]:
df.head()

,Date,Open,High,Low,Close,Volume,Brand_Name,Ticker,Industry_Tag,Country,Dividends,Stock Splits,Capital Gains
0,2025-07-03 00:00:00-04:00,6.630000,6.740000,6.615000,6.640000,4209664.0,peloton,PTON,fitness,usa,0.0,0.0,NaN
1,2025-07-03 00:00:00-04:00,106.750000,108.370003,106.330101,107.339996,560190.0,crocs,CROX,footwear,usa,0.0,0.0,NaN
2,2025-07-03 00:00:00-04:00,122.629997,123.050003,121.550003,121.930000,36600.0,adidas,ADDYY,apparel,germany,0.0,0.0,NaN
3,2025-07-03 00:00:00-04:00,221.705002,224.009995,221.360001,223.410004,29295154.0,amazon,AMZN,e-commerce,usa,0.0,0.0,NaN
4,2025-07-03 00:00:00-04:00,212.145004,214.649994,211.810104,213.550003,34697317.0,apple,AAPL,technology,usa,0.0,0.0,NaN

In [73]:
df['Date'] = pd.to_datetime(df['Date'],utc=True).dt.date        # Without .dt, Pandas wouldn’t know you want to pick apart the datetime into pieces.

In [74]:
df.head()

,Date,Open,High,Low,Close,Volume,Brand_Name,Ticker,Industry_Tag,Country,Dividends,Stock Splits,Capital Gains
0,2025-07-03,6.630000,6.740000,6.615000,6.640000,4209664.0,peloton,PTON,fitness,usa,0.0,0.0,NaN
1,2025-07-03,106.750000,108.370003,106.330101,107.339996,560190.0,crocs,CROX,footwear,usa,0.0,0.0,NaN
2,2025-07-03,122.629997,123.050003,121.550003,121.930000,36600.0,adidas,ADDYY,apparel,germany,0.0,0.0,NaN
3,2025-07-03,221.705002,224.009995,221.360001,223.410004,29295154.0,amazon,AMZN,e-commerce,usa,0.0,0.0,NaN
4,2025-07-03,212.145004,214.649994,211.810104,213.550003,34697317.0,apple,AAPL,technology,usa,0.0,0.0,NaN

In [75]:
df = df.round(2)            # rounds off every numerical value

In [76]:
df.head()

,Date,Open,High,Low,Close,Volume,Brand_Name,Ticker,Industry_Tag,Country,Dividends,Stock Splits,Capital Gains
0,2025-07-03,6.63,6.74,6.61,6.64,4209664.0,peloton,PTON,fitness,usa,0.0,0.0,NaN
1,2025-07-03,106.75,108.37,106.33,107.34,560190.0,crocs,CROX,footwear,usa,0.0,0.0,NaN
2,2025-07-03,122.63,123.05,121.55,121.93,36600.0,adidas,ADDYY,apparel,germany,0.0,0.0,NaN
3,2025-07-03,221.71,224.01,221.36,223.41,29295154.0,amazon,AMZN,e-commerce,usa,0.0,0.0,NaN
4,2025-07-03,212.15,214.65,211.81,213.55,34697317.0,apple,AAPL,technology,usa,0.0,0.0,NaN

In [77]:
df = df[df['Country'].isin(['usa'])]

In [78]:
df.head()

,Date,Open,High,Low,Close,Volume,Brand_Name,Ticker,Industry_Tag,Country,Dividends,Stock Splits,Capital Gains
0,2025-07-03,6.63,6.74,6.61,6.64,4209664.0,peloton,PTON,fitness,usa,0.0,0.0,NaN
1,2025-07-03,106.75,108.37,106.33,107.34,560190.0,crocs,CROX,footwear,usa,0.0,0.0,NaN
3,2025-07-03,221.71,224.01,221.36,223.41,29295154.0,amazon,AMZN,e-commerce,usa,0.0,0.0,NaN
4,2025-07-03,212.15,214.65,211.81,213.55,34697317.0,apple,AAPL,technology,usa,0.0,0.0,NaN
5,2025-07-03,76.26,77.03,75.58,76.39,11545304.0,nike,NKE,apparel,usa,0.0,0.0,NaN

Daily Percent Change

In [79]:
df['Daily_Return_%'] = df.groupby('Ticker')['Close'].pct_change() * 100

In [80]:
df = df.round(2)

In [81]:
df = df[df['Daily_Return_%'].notna()]

Moving Averages

In [82]:
df['MA_7'] = df.groupby('Ticker')['Close'].transform(lambda x:x.rolling(7).mean()) 
df['MA_30'] = df.groupby('Ticker')['Close'].transform(lambda x:x.rolling(30).mean())  # Unlike apply, which would collapse results, transform returns a column of the same length as the original dataframe.

Volatility

In [83]:
df['Volatility_7'] = df.groupby('Ticker')['Close'].transform(lambda x:x.rolling(7).std())

In [84]:
df.tail()

,Date,Open,High,Low,Close,Volume,Brand_Name,Ticker,Industry_Tag,Country,Dividends,Stock Splits,Capital Gains,Daily_Return_%,MA_7,MA_30,Volatility_7
310116,2000-01-03,31.51,31.51,30.43,30.80,6057400.0,costco,COST,retail,usa,0.0,0.0,NaN,5.81,30.931429,33.971000,1.393669
310117,2000-01-03,38.15,38.26,35.94,37.50,53076000.0,cisco,CSCO,technology,usa,0.0,0.0,NaN,5.96,36.380000,39.320667,1.270157
310118,2000-01-03,25.22,25.33,24.69,24.77,2173400.0,3m,MMM,manufacturing,usa,0.0,0.0,NaN,4.12,25.668571,24.640333,1.286590
310120,2000-01-03,7.29,7.34,7.10,7.17,882200.0,nordstrom,JWN,retail,usa,0.0,0.0,NaN,4.06,7.000000,6.445333,0.140475
310121,2000-01-03,5.73,5.79,5.43,5.48,5825700.0,american eagle outfitters,AEO,apparel,usa,0.0,0.0,NaN,9.60,5.094286,4.455333,0.275914

KeyboardInterrupt: